<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	 <EnforceExternalCodeAnalysisRules>true</EnforceExternalCodeAnalysisRules>
  </PropertyGroup>

  <PropertyGroup>
  	<AnalysisLevel>8-ALL</AnalysisLevel>
  	<EnableNETAnalyzers>true</EnableNETAnalyzers>
  	<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="KVKarco.ValidationAssistant.UnitTests" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.0" />
	  <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.8" />
	</ItemGroup>

</Project>
