using System.Collections.ObjectModel;
using System.Text;

namespace KVKarco.ValidationAssistant.Internal.FailureAssets;

/// <summary>
/// Represents the abstract base class for different types of rule failures encountered during validation.
/// This class provides common properties for identifying the failed rule, its context (path),
/// and a high-level explanation. It also defines abstract members for managing specific validation failures
/// that might be associated with a rule.
/// </summary>
internal abstract class RuleFailure
{
    /// <summary>
    /// Initializes a new instance of the <see cref="RuleFailure"/> class.
    /// </summary>
    /// <param name="path">The property path associated with this rule failure (can be empty for non-property specific rules).</param>
    /// <param name="info">Metadata and configuration details for this rule failure.</param>
    /// <param name="explanation">A high-level textual explanation of why the rule failed.</param>
    protected RuleFailure(string path, RuleFailureInfo info, string explanation)
    {
        Path = path;
        Info = info;
        Explanation = explanation;
    }

    /// <summary>
    /// Gets the property path related to where this rule failure occurred.
    /// For non-property specific rules (e.g., logical rules), this might be an empty string.
    /// </summary>
    public string Path { get; }

    /// <summary>
    /// Gets the <see cref="RuleFailureInfo"/> containing metadata and configuration
    /// for this specific rule failure.
    /// </summary>
    public RuleFailureInfo Info { get; }

    /// <summary>
    /// Gets a high-level textual explanation of why the rule failed.
    /// This explanation is typically generated by the rule itself.
    /// </summary>
    public string Explanation { get; }

    /// <summary>
    /// Gets a value indicating whether this rule failure contains any more granular <see cref="ValidationFailure"/> instances.
    /// Derived classes must implement this to specify if they track specific validation issues.
    /// </summary>
    public abstract bool HasValidationFailures { get; }

    /// <summary>
    /// Gets a read-only collection of <see cref="ValidationFailure"/> instances associated with this rule failure.
    /// Derived classes must implement this. For rule failures that don't track specific validation failures,
    /// this might throw <see cref="NotImplementedException"/> or return an empty collection.
    /// </summary>
    public abstract IReadOnlyCollection<ValidationFailure> ValidationFailures { get; }

    /// <summary>
    /// Gets a read-only collection of error messages from the <see cref="ValidationFailure"/> instances
    /// associated with this rule failure.
    /// Derived classes must implement this. For rule failures that don't track specific validation failures,
    /// this might throw <see cref="NotImplementedException"/> or return an empty collection.
    /// </summary>
    public abstract IReadOnlyCollection<string> ValidationFailuresMessages { get; }

    /// <summary>
    /// Adds a <see cref="ValidationFailure"/> to this rule failure.
    /// Derived classes must implement this to define how granular validation failures are collected.
    /// </summary>
    /// <param name="failure">The <see cref="ValidationFailure"/> to add.</param>
    public abstract void AddValidationFailure(ValidationFailure failure);

    /// <summary>
    /// Appends a formatted explanation of this rule failure to the provided <see cref="StringBuilder"/>.
    /// Derived classes must implement this to provide specific formatting for their type of failure.
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> to which the explanation will be appended.</param>
    public abstract void AttachToExplanation(StringBuilder sb);
}

/// <summary>
/// Represents a rule failure that is not tied to a specific property path but rather to a
/// higher-level logical condition or a validator-wide check.
/// Logical rule failures do not contain nested <see cref="ValidationFailure"/> instances.
/// </summary>
internal sealed class LogicalRuleFailure : RuleFailure
{
    /// <summary>
    /// Initializes a new instance of the <see cref="LogicalRuleFailure"/> class.
    /// </summary>
    /// <param name="info">Metadata and configuration details for this logical rule failure.</param>
    /// <param name="explanation">A textual explanation of why the logical rule failed.</param>
    public LogicalRuleFailure(RuleFailureInfo info, string explanation) : base("", info, explanation)
    {
    }

    /// <summary>
    /// Gets a value indicating that a logical rule failure never has nested validation failures.
    /// Always returns <see langword="false"/>.
    /// </summary>
    public sealed override bool HasValidationFailures => false;

    /// <summary>
    /// This property is not implemented for <see cref="LogicalRuleFailure"/> as it does not track
    /// granular <see cref="ValidationFailure"/> instances. Accessing it will result in an exception.
    /// </summary>
    /// <exception cref="NotImplementedException">Always thrown when attempting to access this property.</exception>
    public sealed override IReadOnlyCollection<ValidationFailure> ValidationFailures => throw new NotImplementedException();

    /// <summary>
    /// This property is not implemented for <see cref="LogicalRuleFailure"/> as it does not track
    /// granular validation messages. Accessing it will result in an exception.
    /// </summary>
    /// <exception cref="NotImplementedException">Always thrown when attempting to access this property.</exception>
    public sealed override IReadOnlyCollection<string> ValidationFailuresMessages => throw new NotImplementedException();

    /// <summary>
    /// This method is not implemented for <see cref="LogicalRuleFailure"/> as it does not track
    /// granular <see cref="ValidationFailure"/> instances. Calling it will result in an exception.
    /// </summary>
    /// <param name="failure">The validation failure to add (will cause an exception).</param>
    /// <exception cref="NotImplementedException">Always thrown when attempting to call this method.</exception>
    public sealed override void AddValidationFailure(ValidationFailure failure) => throw new NotImplementedException();

    /// <summary>
    /// Appends a formatted explanation of this logical rule failure to the provided <see cref="StringBuilder"/>.
    /// It includes separators, the rule's title, and its explanation.
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> to which the explanation will be appended.</param>
    public sealed override void AttachToExplanation(StringBuilder sb)
    {
        sb.AppendLine("---------------------------------------------------------------------------");
        sb.AppendLine(Info.Title);
        sb.Append(Explanation);
        sb.AppendLine("---------------------------------------------------------------------------");
    }
}

/// <summary>
/// Represents a rule failure specifically associated with a property during validation.
/// This type of rule failure can contain one or more granular <see cref="ValidationFailure"/> instances
/// that specify issues found within the property's value.
/// </summary>
/// <typeparam name="TProperty">The type of the property that the rule is validating.</typeparam>
internal sealed class PropertyRuleFailure<TProperty> : RuleFailure
{
    /// <summary>
    /// A private list to store individual <see cref="ValidationFailure"/> instances for this property rule.
    /// This list is lazily initialized when the first validation failure is added.
    /// </summary>
    private List<ValidationFailure>? _validationFailures;

    /// <summary>
    /// Initializes a new instance of the <see cref="PropertyRuleFailure{TProperty}"/> class.
    /// </summary>
    /// <param name="property">The <see cref="Undefined{TProperty}"/> instance representing the property and its value.</param>
    /// <param name="path">The property path associated with this rule failure.</param>
    /// <param name="info">Metadata and configuration details for this property rule failure.</param>
    /// <param name="explanation">A high-level textual explanation of why the property rule failed.</param>
    public PropertyRuleFailure(Undefined<TProperty> property, string path, RuleFailureInfo info, string explanation) : base(path, info, explanation)
    {
        Property = property;
    }

    /// <summary>
    /// Gets the <see cref="Undefined{TProperty}"/> instance that encapsulates the property's value
    /// and its state (present/missing, null).
    /// </summary>
    public Undefined<TProperty> Property { get; }

    /// <summary>
    /// Gets a value indicating whether this property rule failure contains any specific <see cref="ValidationFailure"/> instances.
    /// Returns <see langword="true"/> if there are collected validation failures; otherwise, <see langword="false"/>.
    /// </summary>
    public sealed override bool HasValidationFailures => _validationFailures is not null
        && _validationFailures.Exists(x => x.Severity == FailureSeverity.Error || x.Severity == FailureSeverity.Warning);

    /// <summary>
    /// Gets a read-only collection of <see cref="ValidationFailure"/> instances that occurred for this property.
    /// Returns an empty collection if no validation failures have been added.
    /// </summary>
    public sealed override IReadOnlyCollection<ValidationFailure> ValidationFailures => _validationFailures is not null
        ? _validationFailures.Where(x => x.Severity == FailureSeverity.Error || x.Severity == FailureSeverity.Warning).ToArray()
        : [];

    /// <summary>
    /// Gets a read-only collection of error messages from the <see cref="ValidationFailure"/> instances
    /// associated with this property rule, specifically filtering for failures with <see cref="FailureSeverity.Error"/>.
    /// Returns an empty collection if no error messages are present.
    /// </summary>
    public sealed override IReadOnlyCollection<string> ValidationFailuresMessages =>
        _validationFailures is not null
        ? new ReadOnlyCollection<string>(_validationFailures.Where(x => x.Severity == FailureSeverity.Error).Select(x => x.Message).ToArray())
        : [];

    /// <summary>
    /// Adds a <see cref="ValidationFailure"/> to the collection of failures for this property rule.
    /// The internal list of validation failures is initialized if it does not already exist.
    /// </summary>
    /// <param name="failure">The <see cref="ValidationFailure"/> instance to add.</param>
    public sealed override void AddValidationFailure(ValidationFailure failure)
    {
        _validationFailures ??= []; // Initialize list if null
        _validationFailures.Add(failure); // Add the new validation failure
    }

    /// <summary>
    /// Appends a formatted explanation of this property rule failure to the provided <see cref="StringBuilder"/>.
    /// It includes separators, the rule's title, its explanation, the property's value,
    /// and then appends explanations for any nested <see cref="ValidationFailure"/> instances.
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> to which the explanation will be appended.</param>
    public sealed override void AttachToExplanation(StringBuilder sb)
    {
        sb.AppendLine("---------------------------------------------------------------------------");
        sb.AppendLine(Info.Title);
        sb.Append(Explanation);

        if (_validationFailures is not null && _validationFailures.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("Property value: ");
            sb.AppendLine(Property.ToString()); // Append string representation of the property's value

            for (int i = 0; i < _validationFailures.Count; i++)
            {
                _validationFailures[i].AttachToExplanation(sb); // Append explanation for each nested validation failure
            }
        }

        sb.AppendLine("---------------------------------------------------------------------------");
    }
}